name: Android Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
      - run: ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: legal-assistant-apk
          path: app/build/outputs/apk/debug/*.apk
